Bug 23230: Fix build error on Windows 64
Fix the following build error we have when building for Windows 64:
/var/tmp/build/firefox-af0ca6a886c7/media/libcubeb/src/cubeb_wasapi.cpp:1596:46:
  error: cast from cubeb_devid {aka void*} to int loses precision
 [-fpermissive]

We fix that by using %p instead of %x to remove the need for a cast.